name: Python Unit Tests

# Defines when the action should run. This example triggers on push and pull requests to the main branch.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Jobs that the workflow will execute
jobs:
  test:
    name: "Test ${{ matrix.os }} with Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v3

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions uv
          uv pip install --system numpy==1.26.4 scipy==1.13.1 mujoco==3.2.7 mujoco_mjx==3.2.7
          uv pip install --system brax==0.12.1 playground==0.0.3 pyyaml

      - name: "Trigger git clone mujoco_menagerie"
        run: |
          python -c "import mujoco_playground"

      - name: "Test with tox for ${{ matrix.os }}"
        run: |
          tox
        env:
          PLATFORM: ${{ matrix.os }}
